In [197]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv


--2022-09-10 13:54:32--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.3’

data.csv.3          100%[===================>]   1.41M  4.41MB/s    in 0.3s    

2022-09-10 13:54:33 (4.41 MB/s) - ‘data.csv.3’ saved [1475504/1475504]



### Question 1
What's the version of NumPy that you installed?

In [198]:
import numpy as np
np.__version__

'1.21.5'

In [199]:
import pandas as pd
df = pd.read_csv('data.csv')

### Question 2

How many records are in the dataset?

In [200]:
df.shape[0]

11914

### Question 3

Who are the most frequent car manufacturers (top-3) according to the dataset?

In [201]:
df.groupby('Make')['Make'].count().sort_values(ascending=False).head(3)

Make
Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4

What's the number of unique Audi car models in the dataset?

In [202]:
df[df.Make == "Audi"].drop_duplicates(subset = ["Model"]).shape[0]

34

### Question 5

How many columns in the dataset have missing values?

In [203]:
df.isnull().sum()[df.isnull().sum()>0].shape[0]

5

### Question 6:
# Does the median value change after filling missing values?

In [204]:
frequent = df['Engine Cylinders'].mode()
median1 =df['Engine Cylinders'].median()
frequent, median1

(0    4.0
 Name: Engine Cylinders, dtype: float64,
 6.0)

In [205]:
df['Engine Cylinders'].fillna(frequent).median()

6.0

### Question 7

In [206]:
X = df[df.Make == "Lotus"][["Engine HP", "Engine Cylinders"]].drop_duplicates()
X = X.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [207]:
XTX = np.matmul(X.T,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [208]:
XTX_INV = np.linalg.inv(XTX)

In [209]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [210]:
w = (XTX_INV.dot(X.T)).dot(y)
w

array([  4.59494481, -63.56432501])